### ISSUE TITLE
Not getting right password from my .init; only after everything is initialized?

### ISSUE THREAD

**Issue by guoweis** [DamienCassou/auth-source-pass#111]
Hi,

This is probably not a bug but just that i don't know how to use this package in my init/config.el file (I'm using doom emacs)

I'm using auth-source-pass to store my gcal credential with the following code in my config.el. However, the org-gal-client-secret with the snippet below ends up with something like `"\205\214p\344V@\377|\303\226#'\241SQq\322\311\231\353\215\211v\356\236\254wX\303[\fZw$\307I\212bPElT\271\221\313\341\223Y...`

But once emacs is up and running, if I re-evaluate this snippet below, everything works.  So i'm curious if anyone could help me get the usage right.

```
(require 'org-gcal)
(setq org-gcal-client-id "``xyz.apps.googleusercontent.com``"
org-gcal-client-secret (auth-source-pass-get 'secret "gcal/somepassword")
org-gcal-fetch-file-alist '((``"someone@gmail.com``" . "~/org/gtd/somecal.org")
))
```

**Comment by DamienCassou** [comment]
It feels like, at this point of your init file, Emacs is not yet setup to decrypt .gpg files yet. You could verify that by adding the following to your init file:

```emacs
(setq my/var (with-current-buffer (find-file-noselect "/home/.../.password-store/gcal/somepassword.gpg") (buffer-substring-no-properties (point-min) (point-max)))
```

When Emacs is loaded, you should have the content of the gpg file inside `my/var`.

**Comment by DamienCassou** [comment]
I'm closing this issue as I don't want to receive issues about this project anymore. They should be sent to emacs-core directly.
