### ISSUE TITLE
[support] Port as arbitrary string ?

### ISSUE THREAD

**Issue by edgar-vincent** [DamienCassou/auth-source-pass#113]
Hello,

First of all, I'd like to thank you for all your incredible work.

I'm trying to install the [subsonic.el](https://git.sr.ht/~amk/subsonic.el) package. It identifies the host it connects to by the port it has defined in an `auth-source`, which, in this case, should be `subsonic`, with:
```
(defvar subsonic-auth (let ((auth (auth-source-search :port "subsonic")))
                        (when auth
                          (car auth))))
```

When I define a host in `~/.authinfo.gpg` with the `subsonic` port/service name, evaluating `(auth-source-search :port "subsonic")` returns it. However, if add a `pass` entry named `my.host:subsonic` containing:
```
`mypassword`
user: `myuser`
host: `my.host`
port: subsonic
```
I get no results. Is this expected? Or am I doing something wrong?

Merci beaucoup !

EV

**Comment by DamienCassou** [comment]
I find it a bit weird to get the host by searching for all entries with port `subsonic`. That being said, I guess searching for an entry from just a port *is* actually part of the auth-source protocol so it should probably be implemented in auth-source-pass as well. Feel free to send a PR if you want to fix it.

Add this to your init.el for a possible workaround:

```emacs
(setq subsonic-auth (car (auth-source-search :host "my.host" :port "subsonic")
```

**Comment by edgar-vincent** [comment]
I find it a bit weird too, but, as you say, if it works with `.authinfo`, it should probably also work with `auth-source-pass` too. I'm not a programmer but I'll have a look.
 
Thanks!

**Comment by DamienCassou** [comment]
I'm closing this issue as I don't want to receive issues about this project anymore. They should be sent to emacs-core directly.
