### ISSUE TITLE
User is not recognized when using caldav

### ISSUE THREAD

**Issue by Titan-C** [DamienCassou/auth-source-pass#63]
Thank you for this package, using pass only is nicer than keeping track of it and the authinfo file.

I have been dealing with this package for quite a while and it doesn't completely work. Issue #46 was extremely helpful to get my smtp config working. But I have failed with org-caldav.

Reading your init.el @DamienCassou  I understand I should set the user in and url like:
```
(setq org-caldav-url "https://oscar@cloud.najera.pw/remote.php/dav/calendars/oscar")
```
If my passwordstore fie is on `cloud.najera.pw/oscar.gpg` running `org-caldav-sync` *fails* with:

```Contacting host: cloud.najera.pw:443
auth-password-store: searching for ’cloud.najera.pw:https’ in entry names (user: nil)
auth-password-store: no match found
auth-password-store: searching for ’cloud.najera.pw’ in entry names (user: nil)
auth-password-store: no match found
auth-password-store: searching for ’najera.pw:https’ in entry names (user: nil)
auth-password-store: no match found
auth-password-store: searching for ’najera.pw’ in entry names (user: nil)
auth-password-store: no match found
auth-source-search: found 1 results (max 1) matching (:max 1 :host "cloud.najera.pw:443" :port "https")
```

and I'm manually required to give the password for the connection to be established and the sync to happen.

If passwordstore file is on`cloud.najera.pw.gpg` user & password are found and `org-caldav-sync` succeeds.

**Comment by DamienCassou** [comment]
> Thank you for this package, using pass only is nicer than keeping track of it and the authinfo file.

I agree :-).

> I have been dealing with this package for quite a while and it doesn't completely work. Issue #46 was extremely helpful to get my smtp config working. But I have failed with org-caldav.

I hope I can be helpful.

Which version of auth-password-store are you using? The one provided with Emacs 26 or the one in this repository? Which version of it? If you are using anything else than the latest and greatest (3.0) from this repository or melpa, I suggest updating first. I think your problem has been fixed already.

**Comment by Titan-C** [comment]
Hi. I'm using Emacs 25.3 and the package is installed from MELPA where it is still called auth-password-store. I do think it is version 3.0, the date is matched for 20180214.
I'll try installing directly from git and report again later.

**Comment by Titan-C** [comment]
I understand less what is going on. I downloaded the version from git and loaded with:
```emacs-lisp
(use-package auth-source-pass
  :load-path "~/dev/auth-password-store/"
  :init
    (setq auth-source-debug t)
    (require 'auth-source-pass)
    (auth-source-pass-enable))
```
But when I call `org-caldav-sync` I get
```
Contacting host: cloud.najera.pw:443
auth-source-backend-parse: invalid backend spec: password-store
auth-source-search: found 0 CACHED results matching (:max 1 :host "cloud.najera.pw:443" :port "https")
```
unfortunalety this is the case with all other use cases. I can't send email either, `password-store` backend is invalid? 
For completenes `password-store` and `pass` are still installed and work correctly.

**Comment by DamienCassou** [comment]
> the package is installed from MELPA

I spent some time this morning releasing a new stable version 4.0.0 with the new library name. I've also sent a PR to melpa to get the new name in there. This won't help you but will make things a bit clearer to debug your problem.

**Comment by DamienCassou** [comment]
> `(auth-source-pass-enable)`

What is the content of `auth-sources` please?

Can you try replacing that with `(setq auth-sources '(password-store))`?

**Comment by Titan-C** [comment]
I just installed the newly released package from MELPA, I unsurprisingly get the same ill behaviour I had from running from git.

> What is the content of auth-sources please?

Its value is (password-store "~/.authinfo" "~/.authinfo.gpg" "~/.netrc")

> Can you try replacing that with (setq auth-sources '(password-store))?

Did that too same problem.

**Comment by mdorman** [comment]
I'm seeing this issue as well.

**Comment by mdorman** [comment]
I'm going to bet that this is a divergence between emacs-25 and emacs-26.  The emacs-25 version of `auth-source` doesn't have `auth-source-backend-parser-functions`---and indeed, if you look at how you *used* to hook things in, you were advising `auth-source-backend-parse`, rather than adding a hook.

Adding back a suitably-adjusted `(advice-add 'auth-source-backend-parse :before-until #'auth-source-pass-backend-parse)` seems to work.  I imagine that could just be done conditionally on the existence of `auth-source-backend-parser-functions`?

**Comment by DamienCassou** [comment]
Thank you very much @mdorman! Can you please both try #66?

**Comment by DamienCassou** [comment]
I merged the PR. Please reopen the issue if 'master' is still not working for you.

**Comment by Titan-C** [comment]
Hi. The new version does fix the problem with the backend being invalid. Now I'm back to the original issue, the user is not recognized. auth-source-pass only looks for the domain.

**Comment by DamienCassou** [comment]
I failed to find time and interest to fix your issue. Do you still have the problem?

**Comment by Titan-C** [comment]
Yes, I still have the problem. I cannot get `org-caldav-sync` to work with `auth-source-pass`

**Comment by DamienCassou** [comment]
From what I understand, the user is not sent to `auth-source`, only the url. This means that there is no way for auth-source-pass to know about it and to match on `cloud.najera.pw/oscar.gpg`. One workaround would be to add an entry named `cloud.najera.pw:https.gpg` in your password store. This should match.

If you care enough, please open an issue to org-caldav.

I'm closing this issues for now. Please reopen if anything new pops up.

**Comment by DamienCassou** [comment]
I'm closing this issue as I don't want to receive issues about this project anymore. They should be sent to emacs-core directly.
